
import { Raleway } from "next/font/google";
import "./globals.css";



const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // choose weights you need
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
    
      </head>

      <body
        className={`${raleway.variable}  antialiased`}
      >
        {children}

       
      </body>
    </html>
  );
}
